spring:
  datasource:
    url : jdbc:postgresql://localhost:5432/opentutorials
    username: ${NAME}
    password: ${PW}

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
