spring:
  datasource:
    url : jdbc:postgresql://${end_point}:5432/DGU_CECD_DP_DB
    username: ${NAME}
    password: ${PW}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
    show-sql: true
