spring:
  datasource:
    url : jdbc:postgresql://localhost:5432/opentutorials
    username: postgres #${NAME}
    password: Wngurdl1! #${PW}

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true


jwt:
  expiration_time: 86400000 # 1일
  secret: VLdaskfnsdlfnsef #TODO