spring:
  datasource:
    url : jdbc:postgresql://localhost:5432/postgres
    username: 
    password: 

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate.format_sql: true
    show-sql: true
